name: vits-lithuanian
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchaudio>=2.0.0
  - tensorboard>=2.12.0
  - librosa>=0.10.0
  - pydantic>=1.10.7
  - pip

pip:
  - monotonic-align==1.0.0