name: vits
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.0.1
  - torchaudio>=2.0.2
  - tensorboard>=2.13.0
  - librosa>=0.10.0
  - pydantic>=2.1.1
  - pip

pip:
  - monotonic-align==1.0.0